### PR TITLE
logging support

### PR DESCRIPTION
**Pull request by otrosien**

### CODE REVIEW

**Comment by otrosien** [comment]
@oehme base for further discussion (see issue #32)

**Comment by oehme** [comment]
As mentioned in the discussion on #32, I think this is great, they should just be in a sub-package each, so we can easily split them into separate projects if the single jar ever becomes too clunky.

**Comment by otrosien** [comment]
Like that: de.oehme.xtend.contrib.examples.logging.{jul,slf4j,log4j,...}?

**Comment by oehme** [comment]
I'd go for `de.oehme.xtend.contrib.{logging,slf4j,log4j,...}`

I.e. `logging` == JUL, everyone else gets his own top-level package.

**Comment by maxthomas** [comment]
would love to see this merged!

**Comment by otrosien** [comment]
@oehme it's rewritten according to your comment and ready to merge.

**Comment by oehme** [comment]
Thanks for the contribution Oliver! I'll kick off a release soon.

**Pull request merged**
